// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcSOtlkEos3c0sQ89cRqxh-hCcVGcm0Vg',
    appId: '1:828226318282:web:51533bf9d61cb09b90a933',
    messagingSenderId: '828226318282',
    projectId: 'auth-producto-integrador',
    authDomain: 'auth-producto-integrador.firebaseapp.com',
    storageBucket: 'auth-producto-integrador.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbe5mVBMr6bDw9TBwA3cbuWHEpB8qS9Ho',
    appId: '1:828226318282:android:d08cd20f7034122e90a933',
    messagingSenderId: '828226318282',
    projectId: 'auth-producto-integrador',
    storageBucket: 'auth-producto-integrador.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3NbEzXt8FrJzTmSPJvFZzIUs0N-oeC8',
    appId: '1:828226318282:ios:f45135fb3add7ccb90a933',
    messagingSenderId: '828226318282',
    projectId: 'auth-producto-integrador',
    storageBucket: 'auth-producto-integrador.appspot.com',
    iosBundleId: 'com.example.productoIntegrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3NbEzXt8FrJzTmSPJvFZzIUs0N-oeC8',
    appId: '1:828226318282:ios:b2a2f618bb40128290a933',
    messagingSenderId: '828226318282',
    projectId: 'auth-producto-integrador',
    storageBucket: 'auth-producto-integrador.appspot.com',
    iosBundleId: 'com.example.productoIntegrador.RunnerTests',
  );
}
